version: "3.7"

services:
    db:
      container_name: vemn-db
      image: 
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - <path>/db/data:/var/lib/postgresql/data
